### ISSUE TITLE
Michael's Initiation Checklist

### ISSUE THREAD

**Issue by michaelcarroll** [Acucentri/issue-repo#15]
- [x] Create a GitHub account (if you don't have one) and ask a group member to add you to the Acucentri organization.
- [x] Become a member of all appropriate repositories in the Acucentri organization.
- [x] Identify any new repos that should be created, especially if your research topic is new.
- [x] Become a member of the Acucentri shared Google Drive.
- [x] Download _Slack_ on your phone and you will be added to our group chat.
- [x] Look over the current working repository while asking questions to familiarize yourself with the base concepts of our project.
- [x] Tell us what your strengths and weaknesses are.
- [x] Familiarize yourself with the design tools seen in the Google presentation, located in the drive.
- [x] Familiarize yourself with the development tools seen in a the Google presentation, located in the drive.
- [x] Review [Acucentri Policies](https://github.com/Acucentri/issue-repo/blob/master/TeamPolicy.md)
