### ISSUE TITLE
3/1: Assessing Quality Using a Checklist

### ISSUE THREAD

**Issue by CTATE001** [Acucentri/issue-repo#23]
**Team Culture:**
- [x] Build team culture through non-work activities.
        Going to the Perk for coffee, make and share food with team members(Vue did this)
- [x] Regularly recognize and complement team members for their contributions.
        1. Jacob made the original java implemented Solitaire program
        2. Provide constructive feedback 
- [x] Respectfully provide coaching to improve team effectiveness and efficiency.
        Done in person, on Slack, through our [team policy](https://github.com/Acucentri/issue-repo/blob/master/TeamPolicy.md), and our [initiation ](https://github.com/Acucentri/issue-repo/issues/7)and [exit ](https://github.com/Acucentri/issue-repo/issues/12)checklists

**Communication:**
- [x] Set up and use communication tools and processes for effective and rapid information exchange.
       acucentri.slack.com
- [x] Use these tools and processes regularly.
![image](https://user-images.githubusercontent.com/36679368/53269687-29349780-36af-11e9-94a2-01a59d91adea.png)
- [x] Establish and use remote communication tools and processes for distributed team interactions.
       drive.google.com
- [x] Establish and use initiation and exit checklists.
       https://github.com/Acucentri/issue-repo/issues/7
       https://github.com/Acucentri/issue-repo/issues/12
       https://github.com/Acucentri/issue-repo/issues/13
- [x] Establish and use team policy statement.
       https://github.com/Acucentri/issue-repo/blob/master/TeamPolicy.md

**Requirements and Analysis:**
- [ ] Create user stories to capture basic product requirements.
- [x] Analyze, refine, prioritize, select and convert user stories into tasks for development.
        Split each user story into specific Kanban Tasks (view Kanban Board - https://github.com/Acucentri/issue-repo/projects/1)
- [ ] Organize tasks into Epic-story-task packages.
- [x] Experiment with Job Stories as an alternative to User Stories (see 
       https://maherou.github.io/files/CS317/CS317-Links).

**Design:**
- [x] Created basic design documents such as class, interaction and use case.
       https://drive.google.com/file/d/1FM2DjGcnKxyuURKMpfqhHoRoUNacL0l8/view?usp=sharing
       https://drive.google.com/file/d/1DkT8GE2Yil_RD1vDdJyIZoLrnHY3AkxR/view?usp=sharing
- [x] Wrote lightweight design documents
       https://github.com/Acucentri/issue-repo/blob/master/SolitaireAlgorithms_v3
       https://docs.google.com/document/d/1vVL3-nUgzRSwUoos2e5YH5l9DSFVeO_iUesxPySlZKM/edit
- [x] Wrote throw-away prototype code to explore high-risk design elements.
       https://github.com/Acucentri/solitaire-simulator-java
       https://github.com/Acucentri/solitaire-simulator/tree/Michaels_Testing_Arena

**Development:**
- [x] Create GitHub Issues describing major design and development tasks.
       https://github.com/Acucentri/issue-repo
- [x] Establish GitHub Project (Kanban) board.
       https://github.com/Acucentri/issue-repo/projects/1
- [x] Actively manage work by tracking issues on your Kanban board.
       https://github.com/Acucentri/issue-repo/projects/1
- [x] Conduct regular project meetings to assess progress and manage a schedule.
       1. We meet during class periods and after class (specifically on days where class is canceled) to discuss progress on work. We also discuss any challenges faced and how these challenges might affect future work.
- [ ] Use code formatting tool to assure uniform source code.
- [x] Identify and use a coding convention.
       Everything was java doc'd
![image](https://user-images.githubusercontent.com/36679368/57166027-85f2b380-6dbe-11e9-8c9d-4bc8afc488c7.png)
- [ ] Develop in-source documentation via Doxygen.

**Testing:**
- [x] Create basic test capabilities.
       Tests were hard coded
- [ ] Create comprehensive test capabilities.
- [ ] Create and regularly use unit testing.
- [ ] Use a pull-request, code-review integration process for source changes.
- [ ] Automatically monitor and report code coverage.
- [x] Use test-driven development.
       1. When building the Java implementation we created methods to produce a deck that was guaranteed to win and one that was guaranteed to loose. These two methods were used to work through the logic and used to ensure that the results produced were accurate.
- [x] Measure and track software performance.
       https://github.com/Acucentri/solitaire-simulator/blob/master/Simulation%20Results.pdf

**Product Release:**
- [x] Create a unique and traceable release of your software product.
         *look at picture bellow*
- [ ] Make a citable version (with DOI) of your code and make it available on Zenodo or Figshare.
- [x] Generate user and developer documentation.
![image](https://user-images.githubusercontent.com/36679368/53660115-bb461e00-3c22-11e9-8c6d-e4feaf4c8cbc.png)
- [x] Create product branding, e.g. logo family, catchphrase, product description.
<img width="711" alt="Screen Shot 2019-04-30 at 10 33 19 AM" src="https://user-images.githubusercontent.com/25888221/56974535-a8719c00-6b34-11e9-9dc1-5d2a9c41663d.png">
<img width="715" alt="Screen Shot 2019-04-30 at 10 34 49 AM" src="https://user-images.githubusercontent.com/25888221/56974541-ab6c8c80-6b34-11e9-9c24-59604ac27ffb.png">
