### ISSUE TITLE
Member Initiation Checklist

### ISSUE THREAD

**Issue by CTATE001** [Acucentri/issue-repo#7]
This is the initial checklist for members joining Acucentri:
- [ ] Create a GitHub account (if you don't have one) and ask a group member to add you to the Acucentri organization.
- [ ] Become a member of all appropriate repositories in the Acucentri organization.
- [ ] Identify any new repos that should be created, especially if your research topic is new.
- [ ] Become a member of the Acucentri shared Google Drive.
- [ ] Download _Slack_ on your phone and you will be added to our group chat.
- [ ] Look over the current working repository while asking questions to familiarize yourself with the base concepts of our project.
- [ ] Tell us what your strengths and weaknesses are.
- [ ] Familiarize yourself with the design tools seen in the Google presentation, located in the drive.
- [ ] Familiarize yourself with the development tools seen in a the Google presentation, located in the drive.
- [ ] Review [Acucentri Policies](https://github.com/Acucentri/issue-repo/blob/master/TeamPolicy.md)
